import { myProvider } from '@/lib/ai/providers';
import { chartPrompt, updateDocumentPrompt } from '@/lib/ai/prompts';
import { createDocumentHandler } from '@/lib/artifacts/server';
import { streamObject } from 'ai';
import { z } from 'zod';

export const chartDocumentHandler = createDocumentHandler<'chart'>({
  kind: 'chart',
  onCreateDocument: async ({ title, dataStream }) => {
    let draftContent = '';

    // Enhanced schema that supports the new unified chart configuration system
    const { fullStream } = streamObject({
      model: myProvider.languageModel('artifact-model'),
      system: `${chartPrompt}

IMPORTANT: You are now creating charts using the unified configuration system. Always generate charts with:
1. Proper chart configuration including data mapping
2. CSV data or reference to uploaded CSV files
3. Comprehensive chart properties for optimal visualization
4. Each chart should be treated as a NEW chart creation, not an update

When the title includes data mapping hints in brackets like [Data mapping: categories: product, values: sales], use those hints to configure the chart properly.`,
      prompt: title,
      schema: z.object({
        chartData: z.object({
          csvData: z.string().describe('CSV formatted data or reference to uploaded CSV file'),
          charts: z
            .array(
              z.object({
                chartType: z
                  .enum(['bar', 'line', 'pie', 'heatmap', 'radar', 'scatter', 'areaBump'])
                  .describe('Type of chart'),
                title: z.string().describe('Title of the chart'),
                description: z
                  .string()
                  .describe('Description of what the chart represents'),
                chartId: z.string().optional().describe('Unique identifier for the chart'),
                config: z.object({
                  dataMapping: z.any().describe('Data mapping configuration for the chart'),
                  colors: z.object({
                    scheme: z.string().optional()
                  }).optional(),
                  animate: z.boolean().optional(),
                  margin: z.object({
                    top: z.number().optional(),
                    right: z.number().optional(),
                    bottom: z.number().optional(),
                    left: z.number().optional(),
                  }).optional(),
                  // Scale configurations for advanced chart customization
                  xScale: z.object({
                    type: z.enum(['linear', 'log', 'symlog', 'time', 'point']).optional(),
                    min: z.union([z.number(), z.literal('auto')]).optional(),
                    max: z.union([z.number(), z.literal('auto')]).optional(),
                  }).optional(),
                  yScale: z.object({
                    type: z.enum(['linear', 'log', 'symlog', 'time']).optional(),
                    min: z.union([z.number(), z.literal('auto')]).optional(),
                    max: z.union([z.number(), z.literal('auto')]).optional(),
                  }).optional(),
                  // Chart-specific properties
                  nodeSize: z.number().optional(),
                  useMesh: z.boolean().optional(),
                  enablePoints: z.boolean().optional(),
                  pointSize: z.number().optional(),
                  enableCrosshair: z.boolean().optional(),
                  innerRadius: z.number().optional(),
                  enableLabels: z.boolean().optional(),
                  curve: z.string().optional(),
                  legends: z.array(z.any()).optional(),
                  enableGridX: z.boolean().optional(),
                  enableGridY: z.boolean().optional(),
                }).optional().describe('Chart configuration object'),
                data: z
                  .any()
                  .optional()
                  .describe('Processed data for the chart (will be generated by unified system)'),
                useUnifiedSystem: z.boolean().optional().default(true).describe('Flag to indicate using unified chart creation system'),
              }),
            )
            .max(6)
            .describe('Chart configurations (maximum of 6) - each will be created as a new chart'),
        }),
      }),
    });

    for await (const delta of fullStream) {
      const { type } = delta;

      if (type === 'object') {
        const { object } = delta;
        const { chartData } = object;

        if (chartData) {
          // Enhanced content structure that includes unified system markers
          const enhancedChartData = {
            ...chartData,
            systemVersion: 'unified-v2',
            createdAt: new Date().toISOString(),
            charts: chartData.charts?.map(chart => chart ? ({
              ...chart,
              chartId: chart.chartId || `chart-${Math.random().toString(36).substring(2, 15)}`,
              useUnifiedSystem: true,
              config: {
                chartType: chart.chartType,
                title: chart.title,
                description: chart.description,
                margin: { top: 50, right: 130, bottom: 50, left: 60 },
                colors: { scheme: 'nivo' },
                animate: true,
                ...chart.config,
              }
            }) : null).filter(Boolean)
          };

          const content = JSON.stringify(enhancedChartData, null, 2);

          dataStream.writeData({
            type: 'chart-delta',
            content,
          });

          draftContent = content;
        }
      }
    }

    dataStream.writeData({
      type: 'chart-delta',
      content: draftContent,
    });

    return draftContent;
  },
  onUpdateDocument: async ({ document, description, dataStream }) => {
    let draftContent = '';

    // Enhanced update system that creates NEW charts instead of updating existing ones
    const { fullStream } = streamObject({
      model: myProvider.languageModel('artifact-model'),
      system: `${updateDocumentPrompt(document.content, 'chart')}

CRITICAL: When updating charts, you should CREATE NEW CHARTS with the requested changes rather than modifying existing ones. This ensures:
1. Each update generates fresh charts with new IDs
2. All charts use the unified configuration system
3. Proper data mapping and optimization is applied
4. Users get completely new visualizations instead of modified ones

The update description: "${description}" should result in NEW chart creations that incorporate the requested changes.`,
      prompt: `Create new charts based on this update request: ${description}

Current document content: ${document.content}

Generate completely new charts that incorporate the requested changes, don't modify existing ones.`,
      schema: z.object({
        chartData: z.object({
          csvData: z.string().describe('CSV formatted data or reference to uploaded CSV file'),
          charts: z
            .array(
              z.object({
                chartType: z
                  .enum(['bar', 'line', 'pie', 'heatmap', 'radar', 'scatter', 'areaBump'])
                  .describe('Type of chart'),
                title: z.string().describe('Title of the chart'),
                description: z
                  .string()
                  .describe('Description of what the chart represents'),
                chartId: z.string().optional().describe('Unique identifier for the NEW chart'),
                config: z.object({
                  dataMapping: z.any().describe('Data mapping configuration for the chart'),
                  colors: z.object({
                    scheme: z.string().optional()
                  }).optional(),
                  animate: z.boolean().optional(),
                  margin: z.object({
                    top: z.number().optional(),
                    right: z.number().optional(),
                    bottom: z.number().optional(),
                    left: z.number().optional(),
                  }).optional(),
                  // Scale configurations for advanced chart customization
                  xScale: z.object({
                    type: z.enum(['linear', 'log', 'symlog', 'time', 'point']).optional(),
                    min: z.union([z.number(), z.literal('auto')]).optional(),
                    max: z.union([z.number(), z.literal('auto')]).optional(),
                  }).optional(),
                  yScale: z.object({
                    type: z.enum(['linear', 'log', 'symlog', 'time']).optional(),
                    min: z.union([z.number(), z.literal('auto')]).optional(),
                    max: z.union([z.number(), z.literal('auto')]).optional(),
                  }).optional(),
                  // Chart-specific properties
                  nodeSize: z.number().optional(),
                  useMesh: z.boolean().optional(),
                  enablePoints: z.boolean().optional(),
                  pointSize: z.number().optional(),
                  enableCrosshair: z.boolean().optional(),
                  innerRadius: z.number().optional(),
                  enableLabels: z.boolean().optional(),
                  curve: z.string().optional(),
                  legends: z.array(z.any()).optional(),
                  enableGridX: z.boolean().optional(),
                  enableGridY: z.boolean().optional(),
                }).optional().describe('Chart configuration object'),
                data: z
                  .any()
                  .optional()
                  .describe('Processed data for the chart (will be generated by unified system)'),
                useUnifiedSystem: z.boolean().optional().default(true).describe('Flag to indicate using unified chart creation system'),
                isNewChart: z.boolean().optional().default(true).describe('Flag indicating this is a new chart creation'),
              }),
            )
            .max(6)
            .describe('NEW chart configurations (maximum of 6) - all will be created as fresh charts'),
        }),
      }),
    });

    for await (const delta of fullStream) {
      const { type } = delta;

      if (type === 'object') {
        const { object } = delta;
        const { chartData } = object;

        if (chartData) {
          // Enhanced content structure for updates that creates new charts
          const enhancedChartData = {
            ...chartData,
            systemVersion: 'unified-v2',
            updatedAt: new Date().toISOString(),
            updateDescription: description,
            charts: chartData.charts?.map(chart => chart ? ({
              ...chart,
              chartId: `chart-${Math.random().toString(36).substring(2, 15)}-${Date.now()}`, // Always generate new IDs
              useUnifiedSystem: true,
              isNewChart: true,
              config: {
                chartType: chart.chartType,
                title: chart.title,
                description: chart.description,
                margin: { top: 50, right: 130, bottom: 50, left: 60 },
                colors: { scheme: 'nivo' },
                animate: true,
                ...chart.config,
              }
            }) : null).filter(Boolean)
          };

          const content = JSON.stringify(enhancedChartData, null, 2);

          dataStream.writeData({
            type: 'chart-delta',
            content,
          });

          draftContent = content;
        }
      }
    }

    // send final state back after updates
    dataStream.writeData({
      type: 'chart-delta',
      content: draftContent,
    });

    return draftContent;
  },
});
